config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :albums do
    end
  devise_for :users
  root to: 'articles#index'
  resources :articles
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc)}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :articles
  has_many :album
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show

  end

  def edit
    if @article.user != current_user
      flash[:danger] = "You can only edit your own article."
      redirect_to root_path
    end
  end

  def update
    if @article.user != current_user
      flash[:danger] = "You can only edit your own article."
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:sucess] = 'Article has been updated'
        redirect_to @article
      else
        flash.now[:danger] = "Article has not been updated"
        render :edit
      end
    end
  end

  def destroy


    if @article.destroy
      flash[:sucess] = "Article has been deleted"
      redirect_to articles_path
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:sucess] = 'Article has beed created'
      redirect_to articles_path
    else
      flash.now[:danger] = 'Article has not beed created'
      render :new
    end
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for @article do |f| %>
      <% if @article.errors.any? %>
        <div class="errors">
          <h2><%= pluralize(@article.errors.count, "error") %> prevented this article from saving: </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end%>
          </ul>
        </div>
      <% end %>
      <%= f.input :title, placeholder: 'Title of Article' %><br />
      <%= f.input :body, placeholder: 'Body of Article' %>
      <br />
      <%= f.submit 'Update Article', :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Listing all Articles</h1>
<% if user_signed_in? %>
  <%= link_to 'New Article', new_article_path, class: 'btn btn-default btn-lg', id: 'new-article-btn' %>
<% end %>

<% @articles.each do |article| %>
  <div class="well well-lg">
    <div class="article-title">
      <%= link_to article.title, article_path(article) %>
    </div>
    <div class="article-body">
      <%= truncate(article.body, length: 500) %>
    </div>
    <div class="author">
      <% if article.user %>
      <small>Created by: <%= article.user.email %></small>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center">Adding New article</h1>
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for @article do |f| %>
      <% if @article.errors.any? %>
        <div class="errors">
          <h2><%= pluralize(@article.errors.count, "error") %> prevented this article from saving: </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end%>
          </ul>
        </div>
      <% end %>
      <%= f.input :title, placeholder: 'Title of Article' %><br />
      <%= f.input :body, placeholder: 'Body of Article' %>
      <br />
      <%= f.submit 'Create Article', :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<article class="detail-article">
  <h1 class="article-detail-title">
    <%= @article.title %>
  </h1>

  <div class="glyphicon glyphicon-calendar" id="article-date">
    <%= @article.created_at.strftime("%b %d, %y")%>
  </div>

  <div class="article-body">
    <%= @article.body %>
  </div>
  <% if user_signed_in? && current_user == @article.user %>
    <%= link_to "Edit Article", edit_article_path(@article) %>
    <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BDSDPB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>
  <%= render 'shared/main' %>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 text-center">
      <footer role="contentinfo">
        <p><small>Copyright &copy; BDSSPB </small></p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bangladesh Socity at Saint Petersburg,Russia ", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Authors", "#" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Album", albums_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <div class="navbar-right">
              <p class="navbar-text">
                Signed in as <%= "#{current_user.email}" %>
              </p>
            </div>
          <% end %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-8">

      <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>

      <%= yield %>
    </div>

    <div class="col-md-4">
      <%= yield :sidebar %>
    </div>
  </div>
</div>